{% set name = "azure-mgmt-trafficmanager" %}
{% set version = "0.51.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: fc8ae77022cfe52fda4379a2f31e0b857574d536e41291a7b569b5c0f4104186
  
build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common >=1.1,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.trafficmanager

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Microsoft Azure Traffic Manager Client Library for Python'


extra:
  recipe-maintainers:
    - tim-werner
