schema_version: 1

context:
  name: azure-mgmt-trafficmanager
  version: 1.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.zip
  sha256: 35bf1902bf1589d626e35971e5aaa009e884094672b479b798cd1bb8d4f2fdf9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - isodate >=0.6.1,<1.0.0
    - azure-common >=1.1,<2.0.0
    - azure-mgmt-core >=1.3.2,<2.0.0

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.trafficmanager
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Traffic Manager Client Library for Python
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
    - janjagusch
